In [ ]:
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [64]:
training_set=tf.keras.utils.image_dataset_from_directory(
    "C:\\Users\\Lenovo\\Documents\\CropDiseaseDetectionDataset\\New Plant Diseases Dataset(Augmented)\\New Plant Diseases Dataset(Augmented)\\train",
    labels="inferred",#Takes the name of the folders as the labels
    label_mode="categorical",#We have multiclass problem so categorical(e.g. binary or int is also available)
    class_names=None,
    color_mode="rgb",
    batch_size=32,#To speed up the process we can increase the batch size to 64 or 128
    image_size=(128, 128),
    shuffle=True,#If false then data will be feed in alphanumeric order
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    data_format=None,
    # format="tf",
    verbose=True,
)


Found 70295 files belonging to 38 classes.


In [50]:
validation_set=tf.keras.utils.image_dataset_from_directory(
    "C:\\Users\\Lenovo\\Documents\\CropDiseaseDetectionDataset\\New Plant Diseases Dataset(Augmented)\\New Plant Diseases Dataset(Augmented)\\valid",
    labels="inferred",#Takes the name of the folders as the labels
    label_mode="categorical",#We have multiclass problem so categorical(e.g. binary or int is also available)
    class_names=None,
    color_mode="rgb",
    batch_size=32,#To speed up the process we can increase the batch size to 64 or 128
    image_size=(128, 128),
    shuffle=True,#If false then data will be feed in alphanumeric order
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    data_format=None,
    # format="tf",
    verbose=True,
)

Found 17572 files belonging to 38 classes.


In [51]:
for x,y in training_set:
  print(x,x.shape)
  print(y,y.shape)
  break

tf.Tensor(
[[[[114.   107.   115.  ]
   [109.   102.   110.  ]
   [115.25 108.25 116.25]
   ...
   [139.   133.   143.  ]
   [132.75 126.75 136.75]
   [141.   135.   145.  ]]

  [[107.   100.   108.  ]
   [106.    99.   107.  ]
   [112.   105.   113.  ]
   ...
   [136.5  130.5  140.5 ]
   [140.   134.   144.  ]
   [135.75 129.75 139.75]]

  [[108.75 101.75 109.75]
   [104.25  97.25 105.25]
   [100.5   93.5  101.5 ]
   ...
   [136.   130.   140.  ]
   [133.25 127.25 137.25]
   [141.5  135.5  145.5 ]]

  ...

  [[102.75  93.75  98.75]
   [110.   101.   106.  ]
   [100.75  91.75  96.75]
   ...
   [145.75 140.75 147.75]
   [145.25 140.25 147.25]
   [146.25 141.25 148.25]]

  [[109.   100.   105.  ]
   [111.5  102.5  107.5 ]
   [110.25 101.25 106.25]
   ...
   [140.5  135.5  142.5 ]
   [140.25 135.25 142.25]
   [144.5  139.5  146.5 ]]

  [[101.5   92.5   97.5 ]
   [106.    97.   102.  ]
   [105.75  96.75 101.75]
   ...
   [134.75 131.75 138.75]
   [139.   136.   143.  ]
   [132.75 129.75 13

In [52]:
from tensorflow.keras.layers import Dense,MaxPool2D,Conv2D,Flatten
from tensorflow.keras.models import Sequential


In [53]:
model=Sequential()


In [54]:
model.add(Conv2D(filters=32,kernel_size=3,activation='relu',padding='same',input_shape=(128,128,3)))#Input_shaped is passed only to the first layer then the output of the first layer becomes the input to the second layer
model.add(Conv2D(filters=32,kernel_size=3,activation='relu',padding='same'))
model.add(MaxPool2D(pool_size=2,strides=2))#pool_size=2 means a 2x2 window will be used to take the maximum value from each 2x2 block in the input.

c:\Users\Lenovo\anaconda3\envs\ml\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [55]:
model.add(Conv2D(filters=64,kernel_size=3,activation='relu',padding='same'))#Input_shaped is passed only to the first layer then the output of the first layer becomes the input to the second layer
model.add(Conv2D(filters=64,kernel_size=3,activation='relu',padding='same'))
model.add(MaxPool2D(pool_size=2,strides=2))#pool_size=2 means a 2x2 window will be used to take the maximum value from each 2x2 block in the input.

In [56]:
model.add(Conv2D(filters=128,kernel_size=3,activation='relu',padding='same'))#Input_shaped is passed only to the first layer then the output of the first layer becomes the input to the second layer
model.add(Conv2D(filters=128,kernel_size=3,activation='relu',padding='same'))
model.add(MaxPool2D(pool_size=2,strides=2))#pool_size=2 means a 2x2 window will be used to take the maximum value from each 2x2 block in the input.

In [57]:
model.add(Conv2D(filters=256,kernel_size=3,activation='relu',padding='same'))#Input_shaped is passed only to the first layer then the output of the first layer becomes the input to the second layer
model.add(Conv2D(filters=256,kernel_size=3,activation='relu',padding='same'))
model.add(MaxPool2D(pool_size=2,strides=2))#pool_size=2 means a 2x2 window will be used to take the maximum value from each 2x2 block in the input.

In [58]:
from tensorflow.keras.layers import Dropout
model.add(Flatten())
model.add(Dropout(0.5)) # Added Dropout layer with 50% dropout rate
model.add(Dense(1024,activation='relu'))#1024 neurons in the first dense layer
model.add(Dropout(0.5)) # Added another Dropout layer
#Output layer
model.add(Dense(38,activation='softmax'))#38 neurons in the output layer(38 classes)

In [59]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [60]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 128, 128, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 128, 128, 32)   │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 64, 64, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 64, 64, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_3 (Conv2D)               │ (None, 64, 64, 64)     │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 32, 32, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_4 (Conv2D)               │ (None, 32, 32, 128)    │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_5 (Conv2D)               │ (None, 32, 32, 128)    │       147,584 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_2 (MaxPooling2D)  │ (None, 16, 16, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_6 (Conv2D)               │ (None, 16, 16, 256)    │       295,168 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_7 (Conv2D)               │ (None, 16, 16, 256)    │       590,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_3 (MaxPooling2D)  │ (None, 8, 8, 256)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 16384)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 16384)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1024)           │    16,778,240 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 1024)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 38)             │        38,950 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 17,989,446 (68.62 MB)

 Trainable params: 17,989,446 (68.62 MB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
from tensorflow.keras.callbacks import ModelCheckpoint
checkpoint=ModelCheckpoint(
    filepath='model_epoch_{epoch:02d}.h5',
    save_weights_only=False,
    save_best_only=True#Saves every epoch
)
training_history=model.fit(x=training_set,validation_data=validation_set,epochs=5,callbacks=[checkpoint])


In [110]:
from tensorflow.keras.models import load_model
model=load_model('model_epoch_05.h5')
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 128, 128, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 128, 128, 32)   │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 64, 64, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 64, 64, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_3 (Conv2D)               │ (None, 64, 64, 64)     │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 32, 32, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_4 (Conv2D)               │ (None, 32, 32, 128)    │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_5 (Conv2D)               │ (None, 32, 32, 128)    │       147,584 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_2 (MaxPooling2D)  │ (None, 16, 16, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_6 (Conv2D)               │ (None, 16, 16, 256)    │       295,168 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_7 (Conv2D)               │ (None, 16, 16, 256)    │       590,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_3 (MaxPooling2D)  │ (None, 8, 8, 256)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 16384)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 16384)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1024)           │    16,778,240 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 1024)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 38)             │        38,950 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 17,989,448 (68.62 MB)

 Trainable params: 17,989,446 (68.62 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 2 (12.00 B)

In [ ]:
# model.compile(
#     optimizer='adam',
#     loss='categorical_crossentropy',
#     metrics=['accuracy']
# )

# training_history=model.fit(training_set,validation_data=validation_set,epochs=10)


**Model evaluation**

In [ ]:
train_loss,train_acc=model.evaluate(training_set)

2197/2197 ━━━━━━━━━━━━━━━━━━━━ 703s 320ms/step - accuracy: 0.9467 - loss: 0.1584


In [ ]:
print(train_loss,train_acc)

0.15837572515010834 0.9466818571090698


In [ ]:
val_loss,val_acc=model.evaluate(validation_set)
print(val_loss,val_acc)

550/550 ━━━━━━━━━━━━━━━━━━━━ 181s 329ms/step - accuracy: 0.9181 - loss: 0.2472
0.24722641706466675 0.918108344078064


**Save training history**

In [ ]:
# training_history.history

In [ ]:
# import json
# with open("training_hist.json","w") as f:
#     json.dump(training_history.history,f)

**Some other matrics for model evaluation**

In [109]:
class_name=validation_set.class_names
class_name

['Apple___Apple_scab',
 'Apple___Black_rot',
 'Apple___Cedar_apple_rust',
 'Apple___healthy',
 'Blueberry___healthy',
 'Cherry_(including_sour)___Powdery_mildew',
 'Cherry_(including_sour)___healthy',
 'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot',
 'Corn_(maize)___Common_rust_',
 'Corn_(maize)___Northern_Leaf_Blight',
 'Corn_(maize)___healthy',
 'Grape___Black_rot',
 'Grape___Esca_(Black_Measles)',
 'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)',
 'Grape___healthy',
 'Orange___Haunglongbing_(Citrus_greening)',
 'Peach___Bacterial_spot',
 'Peach___healthy',
 'Pepper,_bell___Bacterial_spot',
 'Pepper,_bell___healthy',
 'Potato___Early_blight',
 'Potato___Late_blight',
 'Potato___healthy',
 'Raspberry___healthy',
 'Soybean___healthy',
 'Squash___Powdery_mildew',
 'Strawberry___Leaf_scorch',
 'Strawberry___healthy',
 'Tomato___Bacterial_spot',
 'Tomato___Early_blight',
 'Tomato___Late_blight',
 'Tomato___Leaf_Mold',
 'Tomato___Septoria_leaf_spot',
 'Tomato___Spider_mites Two-spotted_

In [ ]:
test_set=tf.keras.utils.image_dataset_from_directory(
    "C:\\Users\\Lenovo\\Documents\\CropDiseaseDetectionDataset\\test",
    labels="inferred",#Takes the name of the folders as the labels
    label_mode="categorical",#We have multiclass problem so categorical(e.g. binary or int is also available)
    class_names=None,
    color_mode="rgb",
    batch_size=32,#To speed up the process we can increase the batch size to 64 or 128
    image_size=(128, 128),
    shuffle=False,#If false then data will be feed in alphanumeric order
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    data_format=None,
    # format="tf",
    verbose=True,
)

Found 33 files belonging to 1 classes.


In [ ]:
import os
import pandas as pd

test_dir = r"C:\\Users\\Lenovo\\Documents\\CropDiseaseDetectionDataset\\test"

# List all files
filenames = [f for f in os.listdir(test_dir) if f.endswith(".jpg")]

# Extract class name from filename (everything before last underscore)
# Adjust splitting based on your naming convention
labels = [f.split("_")[0] + "_" + f.split("_")[1] if "__" in f else f.split("_")[0] for f in filenames]

# Build a DataFrame
test_df = pd.DataFrame({
    "image_name": filenames,
    "label": labels
})

print(test_df.head())


Empty DataFrame
Columns: [image_name, label]
Index: []


In [ ]:
test_df.columns

Index(['image_name', 'label'], dtype='object')

In [ ]:
import os
import pandas as pd
from tensorflow.keras.preprocessing.image import ImageDataGenerator

test_dir = r"C:\\Users\\Lenovo\\Documents\\CropDiseaseDetectionDataset\\test\\test"

# 1️⃣ List all test images
filenames = [f for f in os.listdir(test_dir) if f.endswith(".JPG")]

# 2️⃣ Extract labels from filenames
def extract_class(filename):
    name = os.path.splitext(filename)[0]  # remove extension
    # Remove trailing digits
    while name and name[-1].isdigit():
        name = name[:-1]
    return name

labels = [extract_class(f) for f in filenames]

# 3️⃣ Create DataFrame
test_df = pd.DataFrame({
    "image_name": filenames,
    "label": labels
})
print(test_df)


# # 5️⃣ Evaluate model
# loss, acc = model.evaluate(test_generator)
# print("Test Accuracy:", acc)


                    image_name                  label
0          AppleCedarRust1.JPG         AppleCedarRust
1          AppleCedarRust2.JPG         AppleCedarRust
2          AppleCedarRust3.JPG         AppleCedarRust
3          AppleCedarRust4.JPG         AppleCedarRust
4               AppleScab1.JPG              AppleScab
5               AppleScab2.JPG              AppleScab
6               AppleScab3.JPG              AppleScab
7          CornCommonRust1.JPG         CornCommonRust
8          CornCommonRust2.JPG         CornCommonRust
9          CornCommonRust3.JPG         CornCommonRust
10      PotatoEarlyBlight1.JPG      PotatoEarlyBlight
11      PotatoEarlyBlight2.JPG      PotatoEarlyBlight
12      PotatoEarlyBlight3.JPG      PotatoEarlyBlight
13      PotatoEarlyBlight4.JPG      PotatoEarlyBlight
14      PotatoEarlyBlight5.JPG      PotatoEarlyBlight
15          PotatoHealthy1.JPG          PotatoHealthy
16          PotatoHealthy2.JPG          PotatoHealthy
17      TomatoEarlyBlight1.J

In [ ]:
# 4️⃣ Create test generator
test_datagen = ImageDataGenerator()  # no rescale needed

test_generator = test_datagen.flow_from_dataframe(
    dataframe=test_df,
    directory=test_dir,
    x_col="image_name",
    y_col="label",
    target_size=(128,128),
    color_mode="rgb",
    class_mode="categorical",
    batch_size=32,
    shuffle=False
)

Found 33 validated image filenames belonging to 8 classes.


In [ ]:
y_pred=model.predict(test_generator)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step 


In [ ]:
y_pred,y_pred.shape#It gives the probability for all 38 class for each image and output will be the max prob

(array([[3.2453390e-05, 1.9584820e-04, 8.3086705e-01, ..., 2.7305996e-06,
         7.4607246e-03, 7.9924427e-03],
        [2.2591148e-05, 4.9865284e-05, 9.6237111e-01, ..., 2.7696508e-06,
         1.5058595e-05, 2.5387277e-04],
        [5.5652137e-05, 6.9501519e-05, 9.0530872e-01, ..., 1.1644120e-04,
         1.3845682e-04, 1.1100210e-03],
        ...,
        [6.0517968e-10, 2.9014910e-14, 1.3634545e-10, ..., 9.9994516e-01,
         5.5998939e-09, 5.1558272e-06],
        [4.2556847e-05, 2.9264534e-08, 1.6913800e-04, ..., 6.5135926e-01,
         1.2793147e-07, 1.0687096e-01],
        [8.9339039e-05, 1.1667996e-08, 3.0420392e-04, ..., 7.5022388e-01,
         6.1314040e-07, 4.1249164e-04]], shape=(33, 38), dtype=float32),
 (33, 38))

In [ ]:
predicted_category=tf.argmax(y_pred,axis=1)#Extracts the class which has maximum probability (axis=1 because we want it column  wise)

In [98]:
predicted_category,predicted_category.shape


(<tf.Tensor: shape=(33,), dtype=int64, numpy=
 array([ 2,  2,  2,  2,  0,  0,  0,  8,  8,  8, 20, 20, 20, 20, 20, 22, 22,
        17, 29, 34, 29, 17, 28, 37, 37, 37, 37, 35, 35, 29, 35, 35, 35])>,
 TensorShape([33]))

In [97]:
true_class_names_test=test_df['label'].values
# true_class_names_test


In [96]:
pred_class_names=[training_set.class_names[i] for i in predicted_category]
# pred_class_names

In [95]:
for true_label,pred_label in zip(true_class_names_test,pred_class_names):
    print(f"True:{true_label}          Predicted:{pred_label}")

True:AppleCedarRust          Predicted:Apple___Cedar_apple_rust
True:AppleCedarRust          Predicted:Apple___Cedar_apple_rust
True:AppleCedarRust          Predicted:Apple___Cedar_apple_rust
True:AppleCedarRust          Predicted:Apple___Cedar_apple_rust
True:AppleScab          Predicted:Apple___Apple_scab
True:AppleScab          Predicted:Apple___Apple_scab
True:AppleScab          Predicted:Apple___Apple_scab
True:CornCommonRust          Predicted:Corn_(maize)___Common_rust_
True:CornCommonRust          Predicted:Corn_(maize)___Common_rust_
True:CornCommonRust          Predicted:Corn_(maize)___Common_rust_
True:PotatoEarlyBlight          Predicted:Potato___Early_blight
True:PotatoEarlyBlight          Predicted:Potato___Early_blight
True:PotatoEarlyBlight          Predicted:Potato___Early_blight
True:PotatoEarlyBlight          Predicted:Potato___Early_blight
True:PotatoEarlyBlight          Predicted:Potato___Early_blight
True:PotatoHealthy          Predicted:Potato___healthy
True:Pota

In [99]:
test_set=tf.keras.utils.image_dataset_from_directory(
    "C:\\Users\\Lenovo\\Documents\\CropDiseaseDetectionDataset\\New Plant Diseases Dataset(Augmented)\\New Plant Diseases Dataset(Augmented)\\valid",
    labels="inferred",#Takes the name of the folders as the labels
    label_mode="categorical",#We have multiclass problem so categorical(e.g. binary or int is also available)
    class_names=None,
    color_mode="rgb",
    batch_size=32,#To speed up the process we can increase the batch size to 64 or 128
    image_size=(128, 128),
    shuffle=False,#If false then data will be feed in alphanumeric order
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    data_format=None,
    # format="tf",
    verbose=True,
)

Found 17572 files belonging to 38 classes.


In [111]:
y_pred=model.predict(test_set)
y_pred,y_pred.shape

550/550 ━━━━━━━━━━━━━━━━━━━━ 176s 321ms/step


(array([[9.9996233e-01, 1.1855942e-05, 8.7266168e-09, ..., 3.2095741e-15,
         1.9372342e-11, 1.8797520e-12],
        [9.9999607e-01, 1.4426870e-06, 3.9671352e-07, ..., 1.8438423e-13,
         9.6070707e-10, 1.8110416e-12],
        [9.9950969e-01, 2.8000385e-04, 2.1456102e-05, ..., 1.3883217e-09,
         1.8915630e-07, 2.8176335e-09],
        ...,
        [4.5020829e-06, 9.7598485e-10, 1.0418308e-05, ..., 5.7202909e-04,
         2.6179336e-07, 9.8523456e-01],
        [1.7998047e-09, 1.3939772e-15, 1.3357168e-09, ..., 1.6410368e-05,
         4.7157826e-11, 9.9754250e-01],
        [1.8202474e-08, 9.4252245e-11, 1.6099332e-08, ..., 1.0979983e-06,
         9.8151634e-07, 8.3951873e-01]], shape=(17572, 38), dtype=float32),
 (17572, 38))

In [103]:
predicted_categories_vali=tf.argmax(y_pred,axis=1)
predicted_categories_vali

<tf.Tensor: shape=(17572,), dtype=int64, numpy=array([20, 20, 20, ..., 20, 20, 20], shape=(17572,))>

In [105]:
true_categories=tf.concat([y for x,y in test_set],axis=0)
y_true=tf.argmax(true_categories,axis=1)
y_true

<tf.Tensor: shape=(17572,), dtype=int64, numpy=array([ 0,  0,  0, ..., 37, 37, 37], shape=(17572,))>

In [108]:
from sklearn.metrics import classification_report
classification_report(y_true,predicted_categories_vali,target_names=class_name)

c:\Users\Lenovo\anaconda3\envs\ml\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Lenovo\anaconda3\envs\ml\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Lenovo\anaconda3\envs\ml\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])


'                                                    precision    recall  f1-score   support\n\n                                Apple___Apple_scab       0.00      0.00      0.00       504\n                                 Apple___Black_rot       0.00      0.00      0.00       497\n                          Apple___Cedar_apple_rust       0.00      0.00      0.00       440\n                                   Apple___healthy       0.00      0.00      0.00       502\n                               Blueberry___healthy       0.00      0.00      0.00       454\n          Cherry_(including_sour)___Powdery_mildew       0.00      0.00      0.00       421\n                 Cherry_(including_sour)___healthy       0.00      0.00      0.00       456\nCorn_(maize)___Cercospora_leaf_spot Gray_leaf_spot       0.00      0.00      0.00       410\n                       Corn_(maize)___Common_rust_       0.00      0.00      0.00       477\n               Corn_(maize)___Northern_Leaf_Blight       0.00      